version: '3'
services:
  mongo:
    image: 'mongo:latest'
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./:/app